INSERT INTO QUESTIONS (`QUESTION_ID`,`QUESTION_TEXT`,`ANSWER_TEXT`) 
VALUES(1, 'What is the Capital of Bangladesh ?','Dhaka is largest city and capital of Bangladesh.');

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(1,1,'Dhaka',1);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(2,1,'Chittagong',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(3,1,'Barisal',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(4,1,'Sylhet',0);


INSERT INTO QUESTIONS (`QUESTION_ID`,`QUESTION_TEXT`,`ANSWER_TEXT`) 
VALUES(2, 'What is the Capital of Australia ?','Canberra is a small city but it is the Capital of Australia.');

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(5,2,'Brisbane',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(6,2,'Sydney',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(7,2,'Canberra',1);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(8,2,'Dubbo',0);

INSERT INTO QUESTIONS (`QUESTION_ID`,`QUESTION_TEXT`,`ANSWER_TEXT`) 
VALUES(3, 'What is the largest Ocean ?','Among the five Oceans Pacific is the largest.');

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(9,3,'North Ocean',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(10,3,'Indian Ocean',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(11,3,'Atlantic',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(12,3,'Pacific',1);

INSERT INTO QUESTIONS (`QUESTION_ID`,`QUESTION_TEXT`,`ANSWER_TEXT`) 
VALUES(4, 'The word CORPULENT is most nearly the same as : ','CORPULENT means FAT');

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(13,4,'INTERIOR',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(14,4,'WEALTHY',0);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(15,4,'FLESHY',1);

INSERT INTO ANSWER_OPTIONS (`OPTION_ID`,`QUESTION_ID`,`OPTION_TEXT`,`IS_CORRECT`)
VALUES(16,4,'CORRUPT',0);
