DROP TABLE IF EXISTS ANSWER_OPTIONS;

DROP TABLE IF EXISTS QUESTIONS;

CREATE TABLE `QUESTIONS` (
  `QUESTION_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `QUESTION_TEXT` varchar(400) DEFAULT NULL,
  `ANSWER_TEXT` varchar(800) DEFAULT NULL,
  PRIMARY KEY (`QUESTION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;


CREATE TABLE `ANSWER_OPTIONS` (
  `QUESTION_ID` bigint(20) NOT NULL,
  `IS_CORRECT` bit(1) DEFAULT NULL,
  `OPTION_ID` bigint(20) DEFAULT NULL,
  `OPTION_TEXT` varchar(255) DEFAULT NULL,  
  KEY `FK_4as369bmkk73ujpl9t2ljeghg` (`QUESTION_ID`),
  CONSTRAINT `FK_4as369bmkk73ujpl9t2ljeghg` FOREIGN KEY (`QUESTION_ID`) REFERENCES `QUESTIONS` (`QUESTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `EXAMS` (
	`EXAM_ID` BIGINT(20) NOT NULL,
	`AVERAGE_SCORE` FLOAT NULL DEFAULT NULL,
	`FULL_SCORE` FLOAT NULL DEFAULT NULL,
	`HIGHEST_SCORE` FLOAT NULL DEFAULT NULL,
	`EXAM_TITLE` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`EXAM_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
